# 由 default.conf include；Compose 服务名解析，勿写 127.0.0.1 端口

upstream edge_chat_api {
    server openim-chat:10008;
}

upstream edge_admin_api {
    server openim-chat:10009;
}

upstream edge_im_api {
    server openim-server:10002;
}

upstream edge_msg_gateway {
    server openim-server:10001;
}

upstream edge_minio {
    server minio:9000;
}

upstream edge_h5 {
    server openim-h5:80;
}

upstream edge_im_admin {
    server im-admin:80;
}

upstream edge_admin_front {
    server openim-admin-front:80;
}

upstream edge_web_front {
    server openim-web-front:80;
}

upstream edge_livekit {
    server livekit:7880;
}
